name: intl_example
description: Example of a Flutter app using the intl library services.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
