name: web_sockets
description: Web Sockets

environment:
  sdk: ^3.0.0-0

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
