name: l10n_example
description: A minimal example of a localized Flutter app

environment:
  sdk: ^3.0.0-0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
