version: "3.9"
services:

  site:
    image: flt-dev
    build:
      context: .
      target: dev
    command: ["make", "serve"]
    env_file: .env
    environment:
      - NODE_ENV=development
      - JEKYLL_ENV=development
    ports:
      - "4002:4002"
      - "35729:35729"
    volumes:
      - ./:/app
      - site_bundle:/usr/local/bundle

volumes:
  site_bundle:
