name: flutter_io_dev_tools

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.1.2
  code_excerpt_updater:
    git: https://github.com/RedBrogdon/code_excerpt_updater.git
  code_excerpter:
    git: https://github.com/RedBrogdon/code_excerpter.git
  linkcheck: ^2.0.6
  yaml: ^2.1.15
  path: ^1.6.2
  github: ^4.1.0
  firebase: ^5.0.3
