name: tabs
description: Sample code for tabs cookbook recipe.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.3

flutter:
  uses-material-design: true
