name: mocking
description: Use the Mockito package to mimic the behavior of services for testing.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.1
  build_runner: ^1.11.0
  flutter_lints: ^1.0.3

flutter:
  uses-material-design: true
