name: background_parsing
description: Background parsing

environment:
  sdk: ^3.0.0-0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
