name: background_parsing
description: Background parsing

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_lints: ^1.0.3

flutter:
  uses-material-design: true
