name: constraints
description: example for ui/layout/constraints
version: 1.0.0

environment:
  sdk: ^3.0.0-0

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
