name: add_language
description: An i18n app example that adds a supported language

environment:
  sdk: ^3.0.0-0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any # Use the pinned version from flutter_localizations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
