name: scrolling
description: A new Flutter project.

environment:
  sdk: ^3.0.0-0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
  path: ^1.8.0
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
