name: counter_app
description: Flutter project for unit testing introduction.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0-0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  test: ^1.20.1

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
