name: error_reporting
description: error reporting

environment:
  sdk: ^3.0.0-0

dependencies:
  flutter:
    sdk: flutter
  sentry_flutter: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
