- platform: 'Android SDK'
  chipsets: 'x64, Arm32, Arm64'
  supported: '21 to 34'
  besteffort: 'N/A'
  unsupported: '20 and earlier'
- platform: 'iOS'
  chipsets: 'Arm64'
  supported: '17'
  besteffort: '12 to 16'
  unsupported: '11 and earlier'
- platform: 'macOS'
  chipsets: 'x64, Arm64'
  supported: '<abbr title="Ventura">13</abbr>, <abbr title="Sonoma">14</abbr>'
  besteffort: '<abbr title="Mojave">10.14</abbr> to <abbr title="Monterey">12</abbr>'
  unsupported: '<abbr title="High Sierra">10.13</abbr> and earlier'
- platform: 'Windows'
  chipsets: 'x64, Arm64'
  supported: '10'
  besteffort: '11'
  unsupported: '8 and earlier'
- platform: 'Debian (Linux)'
  chipsets: 'x64, Arm64'
  supported: '11, 12'
  besteffort: '10'
  unsupported: '9 and earlier'
- platform: 'Ubuntu (Linux)'
  chipsets: 'x64, Arm64'
  supported: '20.04 LTS, 22.04 LTS'
  besteffort: '24.04 LTS'
  unsupported: '23.10 and earlier non-LTS'
- platform: 'Chrome (Web)'
  chipsets: 'N/A'
  supported: '[Latest 2](https://chromereleases.googleblog.com/search/label/Stable%20updates)'
  besteffort: '96 to latest 2'
  unsupported: '95 and earlier'
- platform: 'Firefox (Web)'
  chipsets: 'N/A'
  supported: '[Latest 2](https://www.mozilla.org/en-US/firefox/releases/)'
  besteffort: '99 to latest 2'
  unsupported: '98 and earlier'
- platform: 'Safari (Web)'
  chipsets: 'N/A'
  supported: '[Latest 2](https://developer.apple.com/documentation/safari-release-notes/)'
  besteffort: '15.6 to latest 2'
  unsupported: '15.5 and earlier'
- platform: 'Edge (Web)'
  chipsets: 'N/A'
  supported: '[Latest 2](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel)'
  besteffort: '96 to latest 2'
  unsupported: '95 and earlier'
