title: Flutter 中文文档 - Flutter 中文开发者网站 - Flutter
url: https://docs.flutter.cn
main-url: https://flutter.cn
email: cfug-dev@googlegroups.com

google_analytics_id: UA-122680122-1
# google_site_verification: HFqxhSbf9YA_0rBglNLzDiWnrHiK_w4cqDh2YD2GEY4
google_tag_manager_id: G-HPSFTRXK91
baidu_analytics_id: c50919183c6e001b47301f55de682929
default_share_image: /assets/images/cn/flutter-cn-logo.png

show_banner: true

github_username: cfug
branch: main
repo:
  organization: https://github.com/flutter
  this: https://github.com/cfug/flutter.cn
  flutter: https://github.com/flutter/flutter
  samples: https://github.com/flutter/samples
  packages: https://github.com/flutter/packages
  gallery-archive: https://github.com/flutter/gallery
  engine: https://github.com/flutter/engine
  uxr: https://github.com/flutter/uxr
  wonderous: https://github.com/gskinnerTeam/flutter-wonderous-app
dart:
  api: https://api.dart.cn
  sdk:
    channel: stable
sdk:
  channel: stable # When changing this value also update it in src/_assets/js/archive.js
social:
  twitter: https://twitter.com/FlutterDev
  youtube: https://www.youtube.com/@flutterdev
dart-site: https://dart.cn
news: https://news.dartlang.org
api: https://api.flutter-io.cn
main-api: https://main-api.flutter-io.cn
pub: https://pub-web.flutter-io.cn
pub-api: https://pub-web.flutter-io.cn/documentation
pub-pkg: https://pub-web.flutter-io.cn/packages
flutter-medium: https://medium.com/flutter
medium: https://medium.com
dartpad: https://dartpad.cn
gallery-archive: https://gallery.flutter.cn
material: https://m3.material-io.cn
material2: https://m2.material.io
so: https://stackoverflow.com
github: https://github.com
flutter-assets: https://flutter.github.io/assets-for-api-docs/assets
android-dev: https://developer.android.google.cn
apple-dev: https://developer.apple.com
google-blog: https://developers.googleblog.com
developers: https://developers.google.cn
codelabs: https://codelabs.developers.google.cn
flutter-files-cn: https://files.flutter-io.cn # docs.flutter.cn
groups: https://groups.google.com
firebase: https://firebase.google.cn
wonderous: https://wonderous.app/
youtube-site: https://youtube.com

yt:
  watch: 'https://www.youtube.com/watch'
  playlist: 'https://www.youtube.com/playlist?list='

# docs.flutter.cn - bilibili.com
bili:
  set: 'frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen loading="lazy"'
  set-short: 'frameborder="0" allowfullscreen loading="lazy"'
  video: 'https://www.bilibili.com/video'
  embed: 'https://player.bilibili.com/player.html'
  std-size: 'width="560" height="315"'

## Software minimum versions

appmin:
  git_win: 2.27
  git_mac: 2.27
  vscode: 1.86
  android_studio: '2024.1.1 (Koala)'
  intellij_idea: '2024.1'
  android_sdk: 21
  powershell: 5.0
  xcode: '15'
  cocoapods: '1.16'
devmin:
  windows: '64-bit version of Microsoft Windows 10'
  macos: '11 (Big Sur)'
  linux:
    debian: 11
    ubuntu: '20.04 LTS'
targetmin:
  windows: 'Microsoft Windows 10'
  macos: '10.14 (Mojave)'
  linux:
    debian: 10
    ubuntu: '20.04 LTS'
  ios: 12
  android: 'Android API level 21'

## Software current versions

appnow:
  flutter: '3.27.3'
  vscode: '1.96'
  android_studio: '2024.2'
  android_sdk: '35.0.2'
  intellij: '2024.3'
  powershell: 5.1
  xcode: '16'
  ios: '17'
  cocoapods: '1.16'
