name: key_value
description: Key value

environment:
  sdk: ^3.0.0-0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.5
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
