name: retrieve_input
description: Sample code for retrieve_input cookbook recipe.

environment:
  sdk: ^3.0.0-0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
