name: json
description: Sample state management code.

version: 1.0.0+1

environment:
  sdk: '>=2.17.0-0 <3.0.0'

dependencies:
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  flutter_lints: ^1.0.3
