name: opacity_animation
description: Sample code for cookbook.

environment:
  sdk: ^3.0.0-0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
