name: text_field_changes
description: Sample code for text_field_changes

environment:
  sdk: ^3.0.0-0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
