name: null_safety_basics
description: Some code to demonstrate null safety.
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  example_utils:
    path: ../example_utils
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
