name: ffi_examples
description: >-
  Examples showcasing how to use Dart's FFI support for platform integration.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  example_utils:
    path: ../../example_utils
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
